### PR TITLE
Update to add extended distro support and one-liners

### PR DESCRIPTION
**Pull request by CamoCatX**
The title says it all.

### CODE REVIEW

**Comment by spider863644** [comment]
> The title says it all.

I don't understand

**Comment by CamoCatX** [comment]
@spider863644 Is my contribution needed?

**Comment by spider863644** [comment]
> @spider863644 Is my contribution needed?

Yes

**Comment by CamoCatX** [comment]
> > @spider863644 Is my contribution needed?
> 
> 
> 
> Yes

You are welcome to merge it anytime. @spider863644

**Comment by spider863644** [comment]
Thanks ❤

**Pull request merged**
